name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

  owner:
    description: 'The owner of the repository.'
    required: true
  repo:
    description: 'The repository name.'
    required: true
  pull_number:
    description: 'The pull request number.'
    required: true
  token:
    description: 'The GitHub token.'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
